security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    
    providers:
        users_in_memory:
            memory:
                users:
                    admin: 
                        password: '$2y$13$EKODvJVOm6b8DwtpR98VQeul2kFnFwXvKB7TeanOV269YWt4KU8A6'
                        roles: ['ROLE_ADMIN', 'ROLE_USER']
                    user:
                        password: '$2y$13$VguS5Nf7yx6sl90E3qaZleLmb/Bsym3IB5jLTDjVRPWpToJko68rm'
                        roles: ['ROLE_USER']

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        main:
            http_basic: ~
            # stateless: true  # ← THIS FORCES AUTHENTICATION EVERY TIME
            provider: users_in_memory

    access_control:
        - { path: ^/dashboard, roles: ROLE_USER }

